### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by Dorbmon** [VIGGEEN/WickedEngineCMake#1]
```
Error copying directory from "WickedEngineCMake-main/build/_deps/wickedengine-src/WickedEngine/fonts" to "WickedEngineCMake-main/build/WickedEngine/fonts".
make[2]: *** [CMakeFiles/WickedEngineFonts.dir/build.make:80：WickedEngineFonts] 错误 1
make[1]: *** [CMakeFiles/Makefile2:281：CMakeFiles/WickedEngineFonts.dir/all] 错误 2
make: *** [Makefile:103：all] 错误 2
```

**Comment by VIGGEEN** [comment]
Hello!

It seems that the main WickedEngine project was recently updated.

I pushed new changes to this repo to fix the problem you are experiencing. 

Can you check if it works on your end?

Regards, Viktor.

**Comment by Dorbmon** [comment]
> Hello!
> 
> It seems that the main WickedEngine project was recently updated.
> 
> I pushed new changes to this repo to fix the problem you are experiencing.
> 
> Can you check if it works on your end?
> 
> Regards, Viktor.

Really thanks for your great work!

Now it works well!
